# general settings
name: DRCT_SR
model_type: DRCTModelFinal
scale: 1
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Iris-Thousand
    type: UpsampleDataset
    root_path: /home/cati/Desktop/Dev/NotThatIris-Detector
    csv_file: /datasets/Iris-Thousand/train_iris.csv

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Iris-Thousand
    type: UpsampleDataset
    root_path: /home/cati/Desktop/Dev/NotThatIris-Detector
    csv_file: /datasets/Iris-Thousand/test_iris.csv


# network structures
network_g:
  type: DRCT
  upscale: 1
  in_chans: 3
  img_size: 128
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

feat_extractor_path: "/home/cati/Desktop/Dev/NotThatIris-Detector/ckpts/EFFICIENTNET/models/best.ckpt"

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_loss:
    type: WeightedL1Loss
    reduction: mean
  context_loss:
    type: ContextLoss
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: true

  metrics:
    psnr:
      type: WeightedPSNR
      max_pixel_value: 255.0
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: false
